//Mostrar un producto
###
GET http://localhost:8080/api/product/6369cbab14f5c2c8c6586201 HTTP/1.1 HTTP/1.1

//Borrar un producto por ID
###
DELETE http://localhost:8080/api/product/delete/63a0df272d705b27a838ae HTTP/1.1 HTTP/1.1

//Actualizar un producto por ID
###
PUT http://localhost:8080/api/product/update/63a058258a2b90b344e3e906 HTTP/1.1 HTTP/1.1
Content-Type: application/json

{
    "title": "El hobbit",
    "autor": "JRR Tolkien",
    "img": "https://edit.org/photos/images/cat/portadas-libros-big-2019101610.jpg-1300.jpg",
    "price": 10000,
    "__v": 0
}

//Mostrar un carrito por ID
###
GET http://localhost:8080/api/cart/636c81a539b84975205621b2 HTTP/1.1 HTTP/1.1

//Crear un carrito
###
POST http://localhost:8080/api/cart HTTP/1.1

//Borrar un carrito por ID
###
DELETE  http://localhost:8080/api/cart/63a0e0858644dcf2ed69bad332 HTTP/1.1

//Agregar un producto en el carrito
###
POST http://localhost:8080/api/cart/6369cbab14f5c2c8c6586201/product/63a0d1b8349d491ac6ae9ca9 HTTP/1.1

//Borrar un producto del carrito por ID
###
DELETE  http://localhost:8080/api/cart/6369cbab14f5c2c8c6586201/product/63a0d1b8349d491ac6ae9ca9 HTTP/1.1

//Comprar los productos de un carrito y enviar notificaciones.
###
GET http://localhost:8080/api/cart/636c828b17b675e170489dc8/productos HTTP/1.1 HTTP/1.1



